url: http://docs.hpcloud.com/
markdown: md2html
exclude: README.md, Makefile
metrics: false

navigation:
  main:
  - text: Overview
    url: /
  - text: Compute
    url: /compute/
  - text: Object Storage
    url: /object-storage/
  - text: Block Storage
    url: /block-storage/
  - text: Identity Services
    url: /identity/
  - text: Relational Database
    url: /dbaas/
  - text: Language Bindings
    url: /bindings/
  - text: CLIs
    url: /cli/
  - text: FAQ
    url: /faq/
  - text: Site Overview
    url: /site-overview/